name: Increment Version

on:
  push:
    tags:
      - '*.*.*'

jobs:
  verbump:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: 29393916

      - uses: actions/checkout@v2
      - name: Fetch Tag and Version Information
        run: |
          TAG=$(echo "${GITHUB_REF#refs/*/}")
          TAG_MINUS_V=$(echo "${TAG:1}")
          CURRENT_VERSION_ARRAY=($(echo "$TAG_MINUS_V" | tr . '\n'))
          CURRENT_VERSION=$(IFS=. ; echo "${CURRENT_VERSION_ARRAY[*]:0:3}")
          CURRENT_VERSION_ARRAY[2]=$((CURRENT_VERSION_ARRAY[2]+1))
          NEXT_VERSION=$(IFS=. ; echo "${CURRENT_VERSION_ARRAY[*]:0:3}")
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.TAG }}
          token: ${{ steps.github_app_token.outputs.token }}

      - name: Increment Patch Version
        run: |
          echo Incrementing $CURRENT_VERSION to $NEXT_VERSION
          sed -i "s/__versionstr__ = $CURRENT_VERSION/__versionstr__ = $NEXT_VERSION/g" opensearchpy/_version.py
          echo Updating unified-release to $NEXT_VERSION from $CURRENT_VERSION
          sed -i "s/stack_version: ['$CURRENT_VERSION']/stack_version: ['$NEXT_VERSION']/g" .github/workflows/unified-release.yml
          

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          base: main
          branch: 'create-pull-request/patch-main'
          commit-message: Incremented version to ${{ env.NEXT_VERSION }}
          signoff: true
          delete-branch: true
          labels: |
            autocut
          title: '[AUTO] Incremented version to ${{ env.NEXT_VERSION }}.'
          body: |
            I've noticed that a new tag ${{ env.TAG }} was pushed, and incremented the version from ${{ env.CURRENT_VERSION }} to ${{ env.NEXT_VERSION }}.